'use strict';
const {EXERCISES:E,SOURCES,EQUIPMENT}=FitData;
const F=FitEngine;
const STORE='zizailian-v1';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const checked=(a,b)=>a===b?'checked':'';
const selected=(a,b)=>a===b?'selected':'';
const blank=()=>({version:1,profile:null,draft:null,history:[],measurements:[],mealChecks:{},dayOptions:{},session:null});
let state=blank(),storageOkay=true,loadError=false;
try{const raw=localStorage.getItem(STORE);if(raw){state=validateBackup(JSON.parse(raw));}}catch(e){loadError=true;storageOkay=false;}
let route=location.hash.slice(1)||'today',step=0,draft=state.draft||defaultDraft(),editMode=false,reviewMode=false,planTab=0,sceneChoice=null,mealDay=0;
let timerEnd=0,timerInterval=null,toastTimeout;
function defaultDraft(){return{age:'',sex:'',height:'',weight:'',goal:'recomp',weightStrategy:'auto',recentWeightTrend:'',focus:'balanced',experience:'new',equipment:[],maxDumbbell:'',adjustable:false,days:[0,2,4],minutes:30,sleep:'',activity:'low',foodMode:'home',diet:'mixed',budget:'low',allergyTags:[],allergies:'',notes:'',screening:{},health:{symptoms:'',condition:'',pain:'',pregnancy:'',eating:''}};}
function buildPlan(){const options=state.dayOptions?.[F.dateKey()]||{};return F.makePlan(state.profile,state.history,{minutes:options.minutes,skipToday:options.skip===true,measurements:state.measurements});}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));storageOkay=true;return true;}catch(e){storageOkay=false;toast('浏览器未能保存。请立即导出备份，不要关闭页面。');return false;}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('#toast').classList.remove('visible'),3600);}
function nav(to){route=to;location.hash=to;render();window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'today';render();});
function modal(title,body){$('#modal-content').innerHTML=`<div class="modal-head"><h2>${esc(title)}</h2><button class="icon-button" data-action="close" aria-label="关闭窗口">×</button></div>${body}`;if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function field(name,label,value,type='text',extra='',help=''){return `<label class="field"><span class="field-label">${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}>${help?`<span class="field-help">${help}</span>`:''}</label>`;}
function choice(name,value,title,help='',isChecked=false,type='radio'){return `<label class="choice"><input type="${type}" name="${name}" value="${value}" ${isChecked?'checked':''}><span><strong>${title}</strong>${help?`<small>${help}</small>`:''}</span></label>`;}
function selectField(name,label,options,value,help=''){return `<label class="field"><span class="field-label">${label}</span><select name="${name}">${options.map(([v,t])=>`<option value="${v}" ${selected(value,v)}>${t}</option>`).join('')}</select>${help?`<span class="field-help">${help}</span>`:''}</label>`;}
function render(){
 const main=$('#main');
 const validRoutes=['today','plan','food','record','profile','session'];if(!validRoutes.includes(route))route='today';
 $('#navigation').hidden=!state.profile||editMode||route==='session';
 document.body.classList.toggle('has-profile',Boolean(state.profile)&&!editMode);
 if(!state.profile||editMode){renderSetup();return;}
 $('#navigation').innerHTML=[['today','◷','今天'],['plan','▦','计划'],['food','◒','饮食'],['record','▤','记录'],['profile','◎','我的']].map(([id,icon,label])=>`<button data-nav="${id}" class="${route===id?'active':''}" ${route===id?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</button>`).join('');
 const plan=buildPlan();
 if(!plan.valid){main.innerHTML=`<div class="card"><h1>资料需要补充</h1><p>${esc(plan.errors.join(' '))}</p><button class="btn" data-action="edit">编辑资料</button></div>`;return;}
 const prefix=!storageOkay?'<div class="banner">当前不能可靠保存到浏览器。请在“我的”导出备份后再关闭页面。</div>':'';
 if(route==='session'){main.innerHTML=prefix+(plan.safety.eligible?renderSession():safetyCard(plan)+(state.session?'<div class="card"><p>未结束的训练已保留。先保存已完成的记录，暂不继续加练。</p><div class="actions"><button class="btn" data-action="finish">保存已有训练记录</button><button class="btn secondary" data-action="discard-session">放弃未保存训练</button></div></div>':''));return;}
 main.innerHTML=prefix+({today:()=>renderToday(plan),plan:()=>renderPlan(plan),food:()=>renderFood(plan),record:renderRecord,profile:renderProfile}[route]());
}
function renderSetup(){
 const titles=['先认识现在的你','你想练成什么样','用你已经有的器材','给计划加一道健康检查','把训练放进你的生活'];
 const intros=['所有资料在这里填写。数据保存在当前浏览器，不需要账号。','选择最想改善的方向，同时保留全身基础训练。','没有器材也可以开始。有哑铃时，填写单只重量。','如实填写，用来选择普通或适配方案；需要的细节会在本页继续询问。','选你确实有空的日期，计划会为恢复留出间隔。'];
 let content='';
 if(step===0)content=`<div class="grid-2">${field('age','年龄',draft.age,'number','min="10" max="100" step="1" inputmode="numeric" required')}${selectField('sex','生理性别',[['','请选择'],['male','男性'],['female','女性'],['skip','不提供（不估算热量）']],draft.sex)}</div><div class="grid-2">${field('height','身高 · 厘米',draft.height,'number','min="100" max="230" step="0.1" inputmode="decimal" required')}${field('weight','体重 · 公斤',draft.weight,'number','min="25" max="250" step="0.1" inputmode="decimal" required')}</div><div class="note">年龄和体重帮助我们选择起点；后面会按实际健康情况调整。未成年、孕产或需要专业评估的情况，会提供相应的下一步说明。</div><label class="inline-label"><input type="checkbox" name="localConsent" ${draft.localConsent?'checked':''} required><span class="small">我了解资料只保存在当前浏览器；清理网站数据会丢失记录，需要定期导出备份。</span></label>`;
 if(step===1)content=`<label class="field-label">目前最重要的目标</label><div class="choices">${Object.entries(F.GOALS).map(([k,v])=>choice('goal',k,v,{lean:'增加适量肌肉，追求清晰、匀称的线条',recomp:'建立肌肉与线条，先不急着改变体重',build:'逐步增加力量和肌肉量',lose:'温和减少脂肪，保留力量',health:'精力、体能与持续运动'}[k],draft.goal===k)).join('')}</div><div id="lean-fields">${leanFields()}</div><label class="field field-label">最想改善的体型重点</label><div class="choices">${Object.entries(F.FOCUS).map(([k,v])=>choice('focus',k,v,'',draft.focus===k)).join('')}</div>${selectField('experience','运动基础',[['new','刚开始，或几乎没练过'],['return','练过，但停了较长时间'],['regular','已有稳定运动习惯']],draft.experience)}<div class="note">肌肉比例、脂肪分布和骨骼条件会影响外形。选择重点用于调整训练，不保证复制他人身材；腹部训练也不能指定只减腹部脂肪。</div>`;
 if(step===2)content=`<div class="choices">${EQUIPMENT.map(([k,v,h])=>choice('equipment',k,v,h,draft.equipment.includes(k),'checkbox')).join('')}</div><p class="field-help">没有这些器材可以全部不选。短环形弹力带、单杠、杠铃等暂未接入自动排课，可在备注中记录。</p><div id="dumbbell-fields" ${draft.equipment.includes('dumbbell')?'':'hidden'}>${field('maxDumbbell','单只哑铃最大可用重量 · 公斤',draft.maxDumbbell,'number','min="0.1" max="100" step="0.1" inputmode="decimal"','一对各 5 公斤，填 5；这个数字不是起始训练重量。')}<label class="inline-label"><input type="checkbox" name="adjustable" ${draft.adjustable?'checked':''}>哑铃可以调节重量</label></div><label class="field"><span class="field-label">其他器材 / 想补充的情况（可选）</span><textarea name="notes" maxlength="1000" placeholder="例如：瑜伽垫、固定哑铃只有一个重量">${esc(draft.notes)}</textarea><span class="field-help">备注用于保留信息；本版按上面勾选的器材排课，不会自动理解备注中的新器材。</span></label>`;
 if(step===3){const questions=[['symptoms','运动时或近期有胸痛、晕厥、明显异常气短？'],['condition','有慢性病、规律用药，或医生要求限制运动？'],['pain','有持续疼痛、未恢复的伤病，或处于术后恢复期？'],['pregnancy','处于孕期、产后恢复期或哺乳期？'],['eating','有进食障碍史，或近期不明原因的明显体重变化？']];content=questions.map(([key,title])=>`<fieldset class="field" style="border:0;padding:0"><legend class="field-label">${title}</legend><div class="choices" style="grid-template-columns:repeat(3,1fr)">${[['no','没有'],['yes','有'],['unsure','不确定']].map(([v,t])=>choice(`health_${key}`,v,t,'',draft.health[key]===v)).join('')}</div></fieldset>`).join('')+'<div class="note">选择“有”或“不确定”后，下面会出现相关的补充问题。运动和饮食分别判断，资料仍保存在你的设备。</div>';}
 if(step===4)content=`<span class="field-label">哪几天方便运动？</span><div class="choices">${F.DAYS.map((v,i)=>choice('days',i,v,'',draft.days.includes(i),'checkbox')).join('')}</div>${selectField('minutes','每次可用时间',[['20','约 20 分钟'],['30','约 30 分钟'],['45','约 45 分钟'],['60','约 60 分钟']],String(draft.minutes))}<div class="grid-2">${field('sleep','平时每晚睡多久 · 小时',draft.sleep,'number','min="0" max="16" step="0.1" inputmode="decimal" required')}${selectField('activity','日常活动量',[['low','多数时间坐着，走动较少'],['medium','经常走动或站立'],['high','工作活动较多、体力消耗较大']],draft.activity)}</div>${selectField('foodMode','主要在哪里吃',[['home','自己做饭'],['canteen','食堂'],['takeout','外卖 / 餐馆']],draft.foodMode)}<div class="grid-2">${selectField('diet','饮食方式',[['mixed','一般饮食'],['vegetarian','蛋奶素'],['vegan','纯素']],draft.diet)}${selectField('budget','饮食预算偏好',[['low','节省为主，用常见食材'],['medium','适中，兼顾方便'],['flexible','更看重方便与选择']],draft.budget)}</div><span class="field-label">需要避开的食物</span><div class="choices">${[['egg','蛋'],['milk','奶'],['soy','大豆'],['nuts','坚果 / 花生'],['fish','鱼 / 贝类'],['wheat','小麦']].map(([k,t])=>choice('allergyTags',k,t,'',draft.allergyTags.includes(k),'checkbox')).join('')}</div>${field('allergies','其他过敏或饮食限制（可选）',draft.allergies,'text','maxlength="500"','填写其他限制时，本版会暂停具体食谱建议，避免遗漏食物风险。')}`;
 if(step===0)content=content.replace('</div><div class="note">','</div><p class="field-help">身高按厘米填写，例如 1.70 米填 170。体重按公斤填写，1 公斤 = 2 斤，例如 120 斤是 60 公斤，填 60。</p><div class="note">');
 if(step===3)content='<p class="note">保留真实回答。不适用的情况可以选“没有”。我们会进一步区分需要调整的情况，不把“不确定”当成已经患病。</p>'+content+'<div id="screening-details">'+screeningFields()+'</div>';
 const foot=reviewMode?'<button type="button" class="btn secondary" data-action="cancel-review">返回检查结果</button><button class="btn" type="submit">保存修改，重新检查</button>':`${step>0?'<button type="button" class="btn secondary" data-action="setup-back">上一步</button>':editMode?'<button type="button" class="btn secondary" data-action="cancel-edit">取消修改</button>':''}<button class="btn" type="submit">${step===4?'保存资料，生成我的计划':'下一步'} <span aria-hidden="true">→</span></button>`;
 $('#main').innerHTML=`<div class="setup">${loadError?'<div class="banner">上次保存的数据无法读取。为保护旧数据，请先用“导出原始数据”保存副本，再开始填写。<button class="text-button" data-action="raw-backup">导出原始数据</button></div>':''}<div class="page-head"><div><span class="eyebrow">${reviewMode?'核对影响计划的资料':`建立我的计划 · ${step+1} / 5`}</span><h1>${reviewMode?(step===0?'核对年龄、身高和体重':step===1?'调整目标与体重方向':step===4?'调整饮食与时间':'补充与你有关的情况'):titles[step]}</h1><p class="muted">${reviewMode?'已带入你保存的资料，其他信息会保留。请补充或更新与你有关的情况。':intros[step]}</p></div></div>${reviewMode?'':`<div class="step-track" aria-label="第 ${step+1} 步，共 5 步">${titles.map((_,i)=>`<span class="${i<=step?'done':''}"></span>`).join('')}</div>`}<form id="setup-form"><div class="card">${content}<div id="form-error" class="form-error" role="alert"></div></div><div class="onboarding-foot">${foot}</div></form><p class="footer-note">免费使用 · 不接收费 AI 接口 · 资料留在当前浏览器</p>${!state.profile?'<button class="text-button" data-action="import">从备份恢复已有记录</button>':''}</div>`;
 $('#setup-form').addEventListener('submit',e=>{e.preventDefault();setupNext();});
 if(step===2)$('#setup-form [name=maxDumbbell]').disabled=!draft.equipment.includes('dumbbell');
 $('#setup-form').addEventListener('change',e=>{
  if(step===1&&e.target.name==='goal'){readDraft();$('#lean-fields').innerHTML=leanFields();}
  if(step===2){const has=$('#setup-form input[value="dumbbell"]').checked;$('#dumbbell-fields').hidden=!has;$('#setup-form [name=maxDumbbell]').disabled=!has;}
  if(step===3){const prior=structuredClone(draft),oldQuestions=F.screeningQuestions(prior,state.history);readDraft();
   const path=e.target.name.startsWith('health_')?'health.'+e.target.name.slice(7):e.target.name.startsWith('screen_')?'screening.'+e.target.name.slice(7):'';
   if(path){const affected=new Set([path]);const qs=[...oldQuestions,...F.screeningQuestions(draft,state.history)];let more=true;while(more){more=false;for(const q of qs)if(!affected.has('screening.'+q.key)&&(q.dependsOn||[]).some(d=>affected.has(d.includes('.')||['age','height','weight'].includes(d)?d:'screening.'+d))){delete draft.screening[q.key];affected.add('screening.'+q.key);more=true;}}}
   state.draft=structuredClone(draft);$('#screening-details').innerHTML=screeningFields();
  }
 });
}
function leanFields(){
 if(draft.goal!=='lean')return draft.recentWeightTrend==='unexplained'?`<div class="lean-fields"><p>你之前记录过原因不明的体重变化。更换目标后仍需先确认原因，再如实更新这里的情况。</p>${selectField('recentWeightTrend','最近一两个月的体重变化',[['stable','大致稳定，没有意外下降'],['plannedGain','有计划地增加，原因清楚'],['plannedLoss','有计划地减少，原因清楚'],['unexplained','没有刻意改变，却明显下降或变化原因不明'],['unsure','没有留意，或暂时不能判断']],draft.recentWeightTrend,'曾有原因不明的变化时，先核对记录并获得需要的评估，不用改目标来跳过确认。')}</div>`:'';
 return `<div class="lean-fields"><span class="eyebrow">薄肌身材 · 体重方向单独选</span><p>增加适量肌肉，追求清晰、匀称的线条。先选起点，再用记录复盘，不规定统一的体重或体脂率。</p>${selectField('weightStrategy','体重方向',[['auto','根据我的情况给建议'],['gain','小幅增重'],['maintain','先维持体重']],draft.weightStrategy||'auto','你选的方向会保留。资料不足或有健康限制时，会说明下一步。')}${selectField('recentWeightTrend','最近一两个月的体重变化',[['','请选择'],['stable','大致稳定，没有意外下降'],['plannedGain','有计划地增加，原因清楚'],['plannedLoss','有计划地减少，原因清楚'],['unexplained','没有刻意改变，却明显下降或变化原因不明'],['unsure','没有留意，或暂时不能判断']],draft.recentWeightTrend||'','不用猜体脂率。腰围可在“记录”里补充，身体资料继续留在当前设备。')}<p class="field-help">体重增加不等于全部长肌肉；BMI 也不能区分脂肪和肌肉。先稳定训练与恢复，再观察趋势。</p></div>`;
}
function leanGuidance(plan=null,compact=false){
 if(state.profile?.goal!=='lean')return '';
 const g=plan?.weightGuidance||F.weightGuidance(state.profile,state.history,state.measurements);if(!g)return '';
 const t=g.trend||{},has=v=>v!==null&&v!==undefined&&Number.isFinite(Number(v)),signed=(v,d=1)=>(Number(v)>0?'+':'')+Number(v).toFixed(d);
 const preference={auto:'根据我的情况给建议',gain:'小幅增重',maintain:'先维持体重'}[g.requested]||'根据我的情况给建议';
 const metrics=t.enough?`<div class="weight-metrics"><div><small>前段平均体重</small><strong>${has(t.startAverage)?Number(t.startAverage).toFixed(1):'—'} 公斤</strong></div><div><small>后段平均体重</small><strong>${has(t.endAverage)?Number(t.endAverage).toFixed(1):'—'} 公斤</strong></div><div><small>平均每周变化</small><strong>${has(t.weeklyPercent)?signed(t.weeklyPercent,2)+'%':'—'}</strong></div><div><small>同期腰围变化</small><strong>${has(t.waistChangeCm)?signed(t.waistChangeCm)+' 厘米':'记录不足'}</strong></div></div><p class="field-help">${esc(t.from||'')} 至 ${esc(t.to||'')} · ${Number(t.count)||0} 个日期。比较多个日期的平均值，不能据此算出肌肉或脂肪增加了多少。</p>`:`<p class="field-help">当前有 ${Number(t.count)||0} 个可用日期的记录。先积累分布在至少两周的多次测量，再比较趋势；腰围选填。</p>`;
 return `<section class="card weight-guidance ${compact?'compact':''}" data-weight-direction="${esc(g.effectiveStrategy)}"><div class="section-title"><div><span class="eyebrow">薄肌身材 · 当前体重方向</span><h2>${esc(g.label)}</h2></div><span class="pill">你的选择：${esc(preference)}</span></div><p class="weight-title">${esc(g.title)}</p>${compact?'':`<ul class="small">${(g.reasons||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}<div class="weight-review"><strong>${esc(g.review?.title||'根据后续记录复盘')}</strong><p class="small">${esc(compact?g.review?.action||g.review?.detail||'':g.review?.detail||'')}</p>${!compact&&g.review?.action?`<p class="small"><strong>接下来：</strong>${esc(g.review.action)}</p>`:''}</div>${compact?'':metrics+(g.performance?.detail?`<p class="small"><strong>训练与恢复：</strong>${esc(g.performance.detail)}</p>`:'')+(t.notes||[]).map(x=>`<p class="field-help">${esc(x)}</p>`).join('')}<div class="actions"><button class="text-button" data-action="review-screening" data-review-step="1">调整目标与体重方向</button><button class="text-button" ${compact?'data-nav="record"':'data-action="measurement-entry"'}>${compact?'看趋势与复盘':'补充身体记录'}</button>${compact?'':'<button class="text-button" data-action="weight-method">建议怎样得出</button>'}</div>${g.needsInfo&&g.effectiveStrategy!=='review'?'<p class="field-help">当前是起点判断，还需补充相关情况或更多记录。</p>':''}</section>`;
}
function screeningFields(){
 const qs=F.screeningQuestions(draft,state.history);if(!qs.length)return '<p class="field-help">当前回答没有需要追加的详情，可以继续下一步。</p>';
 return '<div class="section-title"><h2>再了解与你有关的几件事</h2></div>'+qs.map(q=>`<div data-screening-key="${esc(q.key)}">${selectField('screen_'+q.key,q.title,[['','请选择'],...q.options],draft.screening?.[q.key]||'',esc(q.help||''))}</div>`).join('');
}
function readDraft(){
 const fd=new FormData($('#setup-form'));
 if(step===0){for(const k of ['age','sex','height','weight'])draft[k]=fd.get(k);draft.localConsent=fd.has('localConsent');}
 if(step===1){for(const k of ['goal','focus','experience'])draft[k]=fd.get(k);if(fd.has('weightStrategy'))draft.weightStrategy=fd.get('weightStrategy');if(fd.has('recentWeightTrend'))draft.recentWeightTrend=fd.get('recentWeightTrend');}
 if(step===2){draft.equipment=fd.getAll('equipment');draft.maxDumbbell=fd.get('maxDumbbell')||'';draft.adjustable=fd.has('adjustable');draft.notes=fd.get('notes');}
 if(step===3){for(const k of Object.keys(draft.health))draft.health[k]=fd.get(`health_${k}`)||'';draft.screening??={};for(const [key,value] of fd)if(key.startsWith('screen_'))draft.screening[key.slice(7)]=value;}
 if(step===4){draft.days=fd.getAll('days').map(Number);for(const k of ['minutes','sleep','activity','foodMode','diet','budget','allergies'])draft[k]=fd.get(k);draft.allergyTags=fd.getAll('allergyTags');}
 state.draft=structuredClone(draft);
}
function setupNext(){
 readDraft();let errors=[];
 if(step===0&&(!draft.localConsent||!draft.sex))errors.push('请选择性别选项，并确认了解本机保存方式。');
 if(step===1&&draft.goal==='lean'&&!draft.recentWeightTrend)errors.push('请选择近期体重变化；不清楚可以选“不确定”。');
 if(step===2&&draft.equipment.includes('dumbbell')&&!(Number(draft.maxDumbbell)>0&&Number(draft.maxDumbbell)<=100))errors.push('请填写单只哑铃最大可用重量。');
 if(step===3){if(Object.values(draft.health).some(x=>!x))errors.push('请回答每一道健康问题，可选择“不确定”。');for(const q of F.screeningQuestions(draft,state.history))if(q.required&&!draft.screening?.[q.key])errors.push('请补充：'+q.title);}
 if(step===4||reviewMode)errors.push(...F.validateProfile(draft));
 if(errors.length){$('#form-error').textContent=errors.join(' ');$('#form-error').scrollIntoView({block:'center'});return;}
 if(loadError){modal('先保护已有数据','<p>上次保存的数据无法读取。请先导出原始副本，再确认重新开始。</p><div class="actions"><button class="btn" data-action="raw-backup">导出原始数据</button><button class="btn danger" data-action="reset-corrupt">我已备份，重新开始</button></div>');return;}
 if(step<4&&!reviewMode){save();step++;renderSetup();window.scrollTo(0,0);return;}
 const startedAt=state.profile?.planStartedAt||F.dateKey();state.profile=structuredClone(draft);sceneChoice=null;state.profile.planStartedAt=startedAt;state.profile.updatedAt=F.dateKey();state.draft=null;state.session=null;
 if(!state.measurements.length)state.measurements.push({date:F.dateKey(),weight:Number(draft.weight),waist:null});
 const saved=save();editMode=false;reviewMode=false;nav('today');
 if(saved){const result=buildPlan().safety;toast(result.eligible?'资料已保存，已按你的情况安排计划。':result.mode==='clarify'?'资料已保存，再确认相关情况后继续。':'资料已保存，请查看适合你的下一步。');}
}
function safetyCard(plan){
 const a=plan.safety,clarify=a.mode==='clarify';
 return `<div class="page-head"><div><span class="eyebrow">我的安排 · 资料已保留</span><h1>${clarify?'再确认一下，计划更适合你':'先安排好下一步'}</h1><p class="muted">${clarify?'只需补充下面相关的情况，不用重填整份资料。':'当前有些情况需要个别评估，暂不自动开启训练。你的真实回答和已有记录都保留。'}</p></div></div><div class="card">${a.urgent?'<div class="note danger">如果现在正在胸痛、接近晕厥或严重气短，请立即停止运动并寻求当地急救帮助。</div>':''}${a.issues.map(x=>`<section class="screening-item"><h2>${esc(x.title)}</h2><p class="small">${esc(x.answer||'')}</p><p class="muted">${esc(x.message)}</p><button class="btn secondary small" ${x.code==='measurements'?'data-nav="record"':`data-action="review-screening" data-review-step="${[0,1].includes(x.step)?x.step:3}"`}>${x.code==='measurements'?'核对身体记录':x.step===0?'查看基础资料':x.step===1?'核对体重变化':'补充相关情况'}</button></section>`).join('')}<div class="actions"><button class="btn" data-action="review-screening" data-review-step="3">继续完善我的安排</button><button class="btn secondary" data-nav="food">查看适用的饮食指导</button></div></div><div class="grid-2"><div class="card"><h2>需要评估时，可以准备这些</h2><p>带上目前的症状、正在使用的药物、平时活动能力，以及想做的运动。请专业人员明确适合的动作、强度和需要避开的情况。</p><p class="field-help">获得具体建议后，在健康详情中如实更新。涉及康复或专项限制时，应遵循个别方案。</p></div><div class="card"><h2>记录与学习继续可用</h2><p>饮食会单独判断适用范围。你仍可查看历史、保存身体记录，或把资料导出到另一台设备。</p><div class="actions"><button class="btn subtle" data-nav="record">我的记录</button><button class="btn subtle" data-action="basics">入门知识</button></div></div></div>`;
}
function weekStrip(plan){return `<div class="week-strip" aria-label="未来七天">${plan.next7.map(d=>`<button class="day ${d.kind==='strength'?'training':''} ${d.date===F.dateKey()?'today':''}" ${d.workoutId?`data-calendar-workout="${esc(d.workoutId)}"`:'disabled'}><strong>${d.date===F.dateKey()?'今天':F.DAYS[d.day]}</strong><span class="small">${d.date.slice(5).replace('-','/')}</span><small>${d.kind==='strength'?'力量':d.kind==='activity'?'轻活动':'恢复'}</small></button>`).join('')}</div>`;}
function timeControls(){const p=state.profile,opt=state.dayOptions?.[F.dateKey()]||{};return `<div class="time-panel"><label for="today-minutes">今天可用时间</label><select id="today-minutes" aria-label="今天可用时间">${[20,30,45,60].filter(n=>n<=Number(p.minutes)).map(n=>`<option value="${n}" ${selected(Number(opt.minutes||p.minutes),n)}>${n} 分钟</option>`).join('')}</select><button class="text-button" data-action="${opt.skip?'unskip-today':'skip-today'}">${opt.skip?'恢复今天原安排':'今天先休息'}</button></div>`;}
function phaseCards(plan){return `<div class="phase-grid">${plan.weeks.map(w=>`<div class="phase-card ${w.week===plan.phase.week?'current':''}"><span class="eyebrow">第 ${w.week} 周</span><h3>${esc(w.title)}</h3><p class="small muted">${esc(w.detail)}</p></div>`).join('')}</div>`;}
function renderToday(plan){
 if(!plan.safety.eligible)return safetyCard(plan)+leanGuidance(plan,true);
 const today=plan.next7.find(d=>d.date===F.dateKey()),workout=today?.kind==='strength'?plan.workouts.find(w=>w.id===today.workoutId):null;
 const done=state.history.some(h=>h.date===F.dateKey()),last=state.history.at(-1),recovery=last&&Date.now()-last.finishedAt<48*3600000;
 const canStart=workout&&!done&&!recovery;const n=F.nutrition(state.profile,state.history,state.measurements);
 const mainTitle=done?'今天的训练，已记录':canStart?'今天，练好这一套':'给恢复留一点时间';
 const recent=state.history.filter(h=>new Date(h.date+'T12:00:00')>=new Date(Date.now()-7*86400000)).length;
 return `<div class="page-head"><div><span class="eyebrow">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span><h1>今天，照着计划来。</h1></div><span class="badge">${plan.adapted?'适配起步':'我的入门计划'} · 第 ${plan.phase.week} 周</span></div><div class="dashboard-grid"><section class="card dark today-hero"><span class="eyebrow">${done?'已完成记录':canStart?'今日力量训练':'今天的安排'}</span><h1>${mainTitle}</h1><p class="muted">${canStart?`${esc(workout.label)} · ${workout.exercises.length} 个动作 · 约 ${workout.minutes} 分钟`:esc(done?'今天不重复加练，记录会用于调整下一次。':recovery?'距离上次全身力量训练不足 48 小时，先恢复。':today?.title||'保持规律作息，为下次训练留好精力。')}</p><div class="tag-row"><span class="badge">${plan.focus}</span><span class="badge">${esc(plan.phase.title)}</span></div>${canStart?`<div class="hero-moves">${workout.exercises.slice(0,3).map(x=>`<span>${esc(E[x.id].name)}</span>`).join('')}</div>`:''}<div class="actions">${state.session?'<button class="btn primary" data-nav="session">继续未完成的训练</button>':canStart?`<button class="btn primary" data-start="${workout.id}">开始今天的训练</button>`:'<button class="btn primary" data-nav="plan">查看我的训练计划</button>'}</div></section><aside class="card food-preview"><span class="eyebrow">今天怎么吃</span><h2>${n.calories?`约 ${n.calories} 千卡`:n.menuAllowed===false?'先确认饮食要求':'从合适的三餐开始'}</h2><p class="muted">${n.protein?`蛋白质参考 ${n.protein[0]}–${n.protein[1]} 克，分散到三餐。`:esc(n.reason||'根据你的饮食条件查看适用建议。')}</p><div class="food-preview-line">${{home:'在家做饭',canteen:'食堂搭配',takeout:'外卖选择'}[state.profile.foodMode]} · ${{low:'常见食材',medium:'方便轮换',flexible:'灵活搭配'}[state.profile.budget]}</div><button class="btn secondary wide" data-nav="food">${n.menuAllowed===false?'查看饮食相关情况':'看三餐搭配与替换'}</button><p class="field-help">数字是起点估算，按长期变化复盘。</p></aside></div>${leanGuidance(plan,true)}${timeControls()}<div class="section-title"><h2>接下来七天</h2><button class="text-button" data-nav="plan">查看详情</button></div>${weekStrip(plan)}<div class="grid-2"><section class="card focus-card"><span class="eyebrow">根据你的记录调整</span><h2>${esc(plan.adjustment.title)}</h2><p>${esc(plan.adjustment.detail)}</p><p class="field-help">近七天已记录 ${recent} 次训练。每次结束后，记下吃力程度与恢复感受。</p></section><section class="card"><span class="eyebrow">为什么这样安排</span><h2>从你能做到的起点出发</h2><ul class="small">${plan.rationale.slice(0,4).map(t=>`<li>${esc(t)}</li>`).join('')}</ul><button class="text-button" data-action="edit">条件变了，调整我的资料</button></section></div><div class="section-title"><h2>四周入门路线</h2></div>${phaseCards(plan)}<p class="footer-note">自在练 · 手机和电脑都能用 · 资料留在当前设备</p>`;
}
function moveRow(x,i){const ex=E[x.id];return `<div class="exercise-row"><span class="exercise-num">${String(i+1).padStart(2,'0')}</span>${ex.imageId?`<img class="exercise-thumb" src="assets/${ex.imageId}-0.jpg" alt="" loading="lazy">`:''}<div class="exercise-title"><h3>${ex.name}</h3><p>${x.sets} 组 × ${esc(x.reps)} · 休息 ${x.rest} 秒</p><p class="small">${esc(x.reason||ex.muscle)}</p>${x.weightSuggestion?`<p class="field-help">${esc(x.weightSuggestion)}</p>`:''}</div><button class="text-button" data-exercise="${ex.id}">怎么做</button></div>`;}
function renderPlan(plan){
 if(!plan.safety.eligible)return safetyCard(plan)+leanGuidance(plan,true);
 planTab=Math.max(0,Math.min(planTab,plan.workouts.length-1));const w=plan.workouts[planTab];
 return `<div class="page-head"><div><span class="eyebrow">${esc(plan.goal)} · ${esc(plan.focus)}</span><h1>你的训练，逐步往前。</h1></div><button class="btn secondary small" data-action="edit">调整资料</button></div>${leanGuidance(plan)}${timeControls()}${weekStrip(plan)}<div class="plan-layout"><div><div class="segmented">${plan.workouts.map((x,i)=>`<button data-plan="${i}" class="${planTab===i?'active':''}">${F.DAYS[x.day]} · ${x.label}</button>`).join('')}</div><div class="card"><div class="section-title" style="margin-top:0"><h2>${esc(w.label)}</h2><span class="badge">约 ${w.minutes} 分钟</span></div><p class="muted">热身 5–8 分钟 → 按顺序完成动作 → 轻松走动和放松。时长为估算，呼吸未恢复就多休息。</p>${w.exercises.map(moveRow).join('')}<div class="actions"><button class="btn" data-start="${w.id}">练这一套</button><button class="btn secondary" data-action="warmup">热身与放松</button></div></div><div class="card"><h2>${esc(plan.adjustment.title)}</h2><p>${esc(plan.adjustment.detail)}</p><p class="field-help">首次选能稳定完成、仍能再做约 3 次的难度；动作有异常不适时停止。</p></div></div><aside><div class="card"><h2>未来七天详情</h2><div class="calendar-list">${plan.next7.map(d=>`<div class="calendar-line"><div><strong>${F.DAYS[d.day]} <small>${d.date.slice(5)}</small></strong><p class="muted small">${esc(d.title)}${d.minutes?' · 约 '+d.minutes+' 分钟':''}</p></div>${d.workoutId?`<button class="text-button" data-calendar-workout="${esc(d.workoutId)}">查看</button>`:'<span class="pill">恢复</span>'}</div>`).join('')}</div></div><div class="card"><h2>安排依据</h2><ul class="small">${plan.rationale.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></aside></div><div class="section-title"><h2>四周路线，每周都看恢复</h2></div>${phaseCards(plan)}<p class="field-help">这是入门路线，到了某一周并不会强制加量。完成程度、用力感受和恢复情况优先。</p>${plan.notes.map(x=>`<div class="note">${esc(x)}</div>`).join('')}<button class="text-button" data-action="sources">查看训练依据和适用范围</button>`;
}
function foodSceneSelection(){
 const date=F.dateKey();
 if(!sceneChoice||sceneChoice.date!==date){
  const hour=new Date().getHours();
  sceneChoice={place:state.profile.foodMode||'home',meal:hour<10?'breakfast':hour<15?'lunch':'dinner',context:'normal',variant:0,date};
 }
 return sceneChoice;
}
function sceneSelect(key,label,options,value){
 return `<label class="field" for="scene-${key}"><span class="field-label">${label}</span><select id="scene-${key}" data-scene-select="${key}">${Object.entries(options).map(([id,title])=>`<option value="${esc(id)}" ${selected(value,id)}>${esc(title)}</option>`).join('')}</select></label>`;
}
function sceneFoodResults(result){
 const s=result.selection;
 const notes=result.notes?.length?`<details class="scene-notes"><summary>份量、配料与用餐提醒</summary><ul>${result.notes.map(note=>`<li>${esc(note)}</li>`).join('')}</ul></details>`:'';
 if(result.status!=='ready')return `<div class="note warning" data-scene-status="${esc(result.status)}"><strong>${result.status==='empty'?'当前没有匹配的搭配':'先核对与你有关的饮食情况'}</strong><p>${esc(result.reason)}</p><button class="btn secondary small" data-action="review-screening" data-review-step="${[1,3,4].includes(result.reviewStep)?result.reviewStep:4}">核对饮食相关资料</button></div>${notes}`;
 const contextNote=s.context==='pre'?'这是训练前小份，不能代替完整正餐。准备正常吃饭时选“普通用餐”，并留出消化时间。':s.context==='post'?'临近正餐时，把这顿当作恢复餐；加餐也计入当天安排。':'选一套即可；加餐按饥饿和当天安排决定。';
 return `<div class="scene-result-head"><div><span class="eyebrow">${esc(FitFood.PLACES[s.place])} · ${esc(FitFood.MEALS[s.meal])}</span><h3>这顿可以这样吃</h3></div><span class="pill">${result.cards.length} 套可选</span></div>
 <p class="scene-context" data-scene-context-note>${contextNote}</p>
 <div class="scene-cards">${result.cards.map((card,i)=>`<article class="scene-meal-card" data-scene-card="${esc(card.id)}">
  <div class="scene-card-top"><span class="scene-number">${String(i+1).padStart(2,'0')}</span><span class="pill">${esc(card.budgetLabel||'常见食物')}</span></div>
  <h3>${esc(card.title)}</h3>
  <ul class="scene-ingredients">${card.items.map(item=>`<li><strong>${esc(item.name)}</strong><span>${esc(item.portion)}</span></li>`).join('')}</ul>
  <p class="scene-why">${esc(card.why)}</p>
  <div class="scene-how"><strong>${s.place==='home'?'简单做法':s.place==='store'?'购买和搭配':s.place==='canteen'?'食堂选菜':'点单提示'}</strong><p>${esc(card.instruction)}</p></div>
  ${card.swaps?.length?`<details class="scene-swaps"><summary>没有这些食物？看看替换</summary><ul>${card.swaps.map(swap=>`<li>${swap.replaces?`<span class="muted">${esc(swap.replaces)} → </span>`:''}<strong>${esc(swap.name)}</strong>：${esc(swap.portion)}</li>`).join('')}</ul><p class="field-help">替换是搭配参考，不代表热量或蛋白质完全相同。包装食品请结合标签看份量。</p></details>`:'<p class="field-help">这套暂时没有其他符合已填限制的替换。</p>'}
 </article>`).join('')}</div>
 <div class="scene-result-foot"><button class="btn secondary" data-action="scene-next" ${result.hasMore?'':'disabled'}>换一套搭配 <span aria-hidden="true">↻</span></button><p class="field-help">${result.hasMore?'只更换本次推荐，份量不会随点击累加。':'符合当前条件的搭配已全部列出；可更换场景继续查看。'}</p></div>${notes}`;
}
function renderFood(plan){
 const p=state.profile,n=F.nutrition(p,state.history,state.measurements),result=FitFood.recommend(p,n,foodSceneSelection());
 const checks=state.mealChecks[F.dateKey()]||{};
 const preferences=[{mixed:'一般饮食',vegetarian:'蛋奶素',vegan:'纯素'}[p.diet]||'一般饮食',{low:'节省为主',medium:'兼顾方便',flexible:'方便优先'}[p.budget]||'节省为主'];
 if(p.allergyTags?.length)preferences.push('已筛选勾选的过敏项');
 return `<div class="page-head scene-page-head"><div><span class="eyebrow">我的饮食安排</span><h1>今天这顿，按场景搭。</h1></div></div>
 ${!plan.safety.eligible?'<div class="banner">饮食与你的训练分别判断。下面只展示当前资料适用的部分。</div>':''}
 <section class="card scene-picker" aria-labelledby="scene-heading"><div class="scene-picker-heading"><div><span class="eyebrow">按场景推荐</span><h2 id="scene-heading">我现在该吃什么</h2></div><span class="badge">每次选一套</span></div>
 <div class="scene-controls">${sceneSelect('place','在哪里吃',FitFood.PLACES,result.selection.place)}${sceneSelect('meal','吃哪一餐',FitFood.MEALS,result.selection.meal)}${sceneSelect('context','与训练的关系（可选）',FitFood.CONTEXTS,result.selection.context)}</div>
 <div class="scene-preferences"><p class="field-help">${preferences.map(esc).join(' · ')}<br>本次选择不改变已存资料。</p><button class="text-button" data-action="review-screening" data-review-step="4">调整饮食偏好</button></div>
 <p class="scene-direction" data-scene-direction><strong>当前搭配方向：${esc({gain:'小幅增重',maintain:'先维持体重',balanced:'均衡饮食',review:'先核对饮食情况'}[result.strategy]||'均衡饮食')}</strong>${result.strategy==='gain'?'<br><span class="field-help">加量只从午餐主食小幅调整，其他餐不重复追加。</span>':''}</p>
 <p class="field-help">参考份量，非精算菜单；不保证达到每日热量和蛋白质目标。</p>
 ${p.allergyTags?.length?'<p class="field-help">已按勾选项筛选食材示例；包装、调料和共享器具仍需核对。餐馆备注不能保证没有过敏原混入。</p>':''}
 <div id="scene-results" aria-live="polite" aria-atomic="false">${sceneFoodResults(result)}</div>
 </section>
 <details class="card weekly-food"><summary>查看七天三餐搭配参考</summary><p class="field-help">按你保存的主要用餐地点展示，每天每餐一套参考；与上面的即时推荐二选一使用，不需要重复吃。</p><div class="segmented" aria-label="七天饮食轮换">${F.DAYS.map((x,i)=>`<button data-meal-day="${i}" class="${mealDay===i?'active':''}" aria-pressed="${mealDay===i}">${x}</button>`).join('')}</div>${['breakfast','lunch','dinner'].map(meal=>{const r=FitFood.recommend(p,n,{place:p.foodMode,meal,context:'normal',variant:mealDay});const c=r.cards[0];return `<div class="meal"><h3>${esc(FitFood.MEALS[meal])}${c?' · '+esc(c.title):''}</h3><p>${c?c.items.map(x=>esc(x.name)+' '+esc(x.portion)).join('；'):esc(r.reason)}</p></div>`;}).join('')}<p class="field-help">这里同样沿用你的饮食限制和当前体重方向；份量为参考，不能替代个别营养安排。</p></details>
 ${leanGuidance(plan)}
 <div class="note"><strong>${{build:'逐步增加肌肉',lose:'温和减少脂肪',recomp:'先建立力量与规律饮食',health:'规律吃饭，支持日常活动'}[n.effectiveGoal]||'先照顾规律饮食'}</strong><p>${esc(n.reason||'把主食、合适的蛋白质食物、蔬菜和水果放进日常三餐，按长期趋势调整。')}</p></div>
 <div class="grid-2"><div class="card dark"><span class="eyebrow">每日能量 · 起点估算</span><h1>${n.calories?`${n.calories} <small>千卡左右</small>`:n.menuAllowed===false?'先确认个别饮食安排':'先用餐盘份量法'}</h1><p class="muted">${n.calories?'不必每天一丝不差。先观察 2–3 周的平均体重、饥饿感和训练表现。':esc(n.reason)}</p>${n.calories?`<p class="small muted">估算维持量约 ${n.maintenance} 千卡；活动系数 ${n.factor}。<button class="text-button" style="color:var(--lime)" data-action="energy">怎样算的</button></p>`:''}</div><div class="card"><span class="eyebrow">每日蛋白质</span><h1>${n.protein?`${n.protein[0]}–${n.protein[1]} <small>克</small>`:'先确认适合的份量'}</h1><p class="muted">${n.protein?'分散到三餐，用普通食物也可以完成。这里指食物含有的蛋白质重量，不是肉的重量。':'需要结合身体组成和具体健康情况判断。'}</p><button class="text-button" data-action="protein">怎样看食物标签</button></div></div>
 <div class="grid-2"><div class="card"><h2>今天的饮食小记录</h2><p class="muted small">记录习惯，不用给自己打“好坏”分。</p>${[['protein','三餐安排了合适的蛋白质食物'],['veg','今天吃了蔬菜和水果'],['regular','正常吃饭，没有极端节食']].map(([k,t])=>`<label class="inline-label"><input type="checkbox" data-food-check="${k}" ${checks[k]?'checked':''}>${t}</label>`).join('')}</div><div class="card"><h2>什么时候需要调整</h2><p>先连续记录 2–3 周。看相同条件下的周平均趋势，别根据某一天体重就减饭。</p><p class="muted">持续疲劳、头晕、异常饥饿、训练明显退步或月经变化时，停止自行减量并寻求专业意见。当前工具不会自动越减越低。</p><button class="text-button" data-nav="record">去记录体重与感受</button></div></div>
 <button class="text-button" data-action="sources">查看饮食依据</button>`;
}

function renderRecord(){
 const sorted=[...state.measurements].sort((a,b)=>a.date.localeCompare(b.date));
 const chart=sorted.length>1?weightChart(sorted):'';
 return `<div class="page-head"><div><span class="eyebrow">我的记录</span><h1>看长期变化，不催自己。</h1></div></div>${leanGuidance()}<div class="grid-2"><div class="card"><h2>体重趋势</h2>${sorted.length>1?chart:'<div class="empty"><strong>给变化一点时间</strong><p class="muted">记录两次后，这里会显示趋势。</p></div>'}<p class="field-help">尽量在早起、如厕后、进食前测量；使用同一台秤、相近衣着，按周看平均变化。</p><button class="text-button" data-action="waist-help">腰围怎么量（选填）</button><form id="measurement-form"><div class="grid-2">${field('weight','体重 · 公斤','','number','min="25" max="250" step="0.1" required inputmode="decimal"')}${field('waist','腰围 · 厘米（可选）','','number','min="30" max="250" step="0.1" inputmode="decimal"')}</div>${field('date','记录日期',F.dateKey(),'date',`max="${F.dateKey()}" required`)}<button class="btn wide" type="submit">保存身体记录</button><div class="form-error" id="measure-error" role="alert"></div></form></div><div class="card"><h2>训练历史 <span class="badge">${state.history.length} 次</span></h2>${state.history.length?state.history.slice().reverse().slice(0,20).map((h,i)=>`<div class="history-row"><div><strong>${esc(h.label)}</strong><p class="muted small">${esc(h.date)} · 完成 ${h.completedSets}/${h.totalSets} 组</p><p class="small">${h.pain?'记录过疼痛':{easy:'比较轻松',right:'刚刚好',hard:'偏吃力'}[h.effort]||'未评分'}</p></div><button class="text-button" data-history="${state.history.length-1-i}">详情</button></div>`).join(''):'<div class="empty"><strong>第一条记录，等你来写</strong><p class="muted">完成一次训练后，重量、次数和感受会保存在这里。</p></div>'}</div></div><div class="card"><h2>最近身体记录</h2>${sorted.length?`<div class="table-wrap"><table><thead><tr><th>日期</th><th>体重</th><th>腰围</th><th>操作</th></tr></thead><tbody>${sorted.slice(-10).reverse().map(x=>`<tr><td>${esc(x.date)}</td><td>${x.weight} kg</td><td>${x.waist??'—'}</td><td><button class="text-button" data-delete-measure="${esc(x.date)}">删除</button></td></tr>`).join('')}</tbody></table></div>`:''}<p class="field-help">同一天再次保存会替换当天身体记录。身体记录不会改写资料页的体重；薄肌目标会结合多日趋势给出复盘建议。更新基础体重可在“我的”修改。</p></div>`;
}
function weightChart(arr){
 const data=arr.slice(-30),min=Math.min(...data.map(x=>x.weight))-1,max=Math.max(...data.map(x=>x.weight))+1;
 const points=data.map((x,i)=>`${30+i/(data.length-1)*480},${130-(x.weight-min)/(max-min)*105}`);
 return `<svg class="chart" viewBox="0 0 540 160" role="img" aria-label="体重从 ${data[0].weight} 公斤到 ${data.at(-1).weight} 公斤"><path d="M30 135H515" stroke="#dce5e2"/><polyline points="${points.join(' ')}" fill="none" stroke="#427e58" stroke-width="3"/>${points.map(pt=>`<circle cx="${pt.split(',')[0]}" cy="${pt.split(',')[1]}" r="4" fill="#102b2c"/>`).join('')}<text x="30" y="155" fill="#586b6c" font-size="13">${data[0].date.slice(5)} · ${data[0].weight} kg</text><text x="510" y="155" text-anchor="end" fill="#586b6c" font-size="13">${data.at(-1).date.slice(5)} · ${data.at(-1).weight} kg</text></svg>`;
}
function renderProfile(){
 const p=state.profile;
 return `<div class="page-head"><div><span class="eyebrow">我的资料与设置</span><h1>计划跟着你调整。</h1></div></div>${p.goal==='lean'?leanGuidance(null,true):'<div class="card lean-entry"><h2>想练成薄肌身材？</h2><p>把清晰、匀称的线条作为目标，再单独选择小幅增重、维持或让工具给建议。已有记录会保留。</p><button class="btn secondary" data-action="lean-goal">选择薄肌目标</button></div>'}<div class="grid-2"><div class="card"><h2>${F.GOALS[p.goal]} · ${F.FOCUS[p.focus]}</h2><p class="muted">${esc(p.age)} 岁 · ${esc(p.height)} 厘米 · ${esc(p.weight)} 公斤</p><div class="tag-row">${p.equipment.length?p.equipment.map(x=>`<span class="badge">${EQUIPMENT.find(y=>y[0]===x)[1]}</span>`).join(''):'<span class="badge">徒手起步</span>'}</div><p>${p.days.map(d=>F.DAYS[d]).join('、')}有空 · 每次 ${p.minutes} 分钟</p><p class="field-help">${esc(p.notes||'你可以随时更新器材、时间、体型重点和健康情况。')}</p><button class="btn wide" data-action="edit" style="margin-top:18px">编辑资料与计划</button></div><div class="card"><h2>我的数据，由我保管</h2><p>资料、训练和饮食记录仅保存在这个浏览器。本工具没有健康数据上传接口、广告追踪或收费入口。</p><p class="muted">手机和电脑各自保存资料，想在另一台设备查看同一份计划，请先导出备份，再在另一台导入。清理浏览器或换访问地址前也请先备份。Safari 与主屏幕版本也可能使用不同存储，请先导出再恢复。</p><div class="actions"><button class="btn" data-action="export">导出备份</button><button class="btn secondary" data-action="import">导入备份</button></div><p class="field-help">备份含健康资料，请保存在自己的文件夹，不要公开分享。</p></div></div><div class="card"><h2>用起来更顺手</h2><div class="download-list"><button class="btn subtle" data-action="help">手机和电脑怎么用</button><button class="btn subtle" data-action="sources">专业依据与开源说明</button><button class="btn subtle" data-action="basics">从零认识训练</button><button class="btn danger" data-action="reset">清空本机全部记录</button></div></div><p class="footer-note">自在练 2.2 · 资料核验：2026 年 9 月 27 日<br>按资料和训练反馈调整入门方案；图示用于学习，不是实时动作检查。</p>`;
}
function showExercise(id){
 const ex=E[id];if(!ex)return;
 const personal=state.profile?F.progression(id,state.history,state.profile.maxDumbbell):'';
 modal(ex.name,`<p class="muted">${ex.muscle} · ${ex.reps} · 组间休息 ${ex.rest} 秒</p>${ex.imageId?`<div class="exercise-photos"><figure><img src="assets/${ex.imageId}-0.jpg" alt="${ex.name}动作位置参考 1" loading="lazy"><figcaption>动作位置参考 1</figcaption></figure><figure><img src="assets/${ex.imageId}-1.jpg" alt="${ex.name}动作位置参考 2" loading="lazy"><figcaption>动作位置参考 2</figcaption></figure></div><p class="field-help">开源静态图示，用于理解姿势，不保证两张照片按完整动作先后排序。请按下方步骤完成；图示不代表你的动作已被检查。${ex.id==='goblet'?'图中为壶铃握法；使用哑铃时需双手托稳一端。':''}</p>`:'<div class="note">这个动作提供文字步骤；没有可靠对应图示时，不用其他动作照片代替。</div>'}<h3 style="margin-top:18px">一步一步做</h3><ol>${ex.steps.map(s=>`<li>${s}</li>`).join('')}</ol><h3 style="margin-top:18px">容易做错的地方</h3><ul>${ex.mistakes.map(s=>`<li>${s}</li>`).join('')}</ul><div class="note"><strong>太难时：</strong>${ex.easier}</div>${personal?`<div class="note"><strong>根据你的记录：</strong>${personal}</div>`:''}<p class="small">出现尖锐痛、麻木、胸痛、眩晕或异常气短时停止，不把疼痛当作有效训练的标志。</p>${ex.source?`<p style="margin-top:14px"><a href="${ex.source}" target="_blank" rel="noopener noreferrer">查看图文来源（外部网页，可能为英文）</a></p>`:'<p class="field-help">中文步骤为本工具原创整理；可带给合格教练确认动作。</p>'}`);
}
function beginWorkout(id){
 const plan=buildPlan();if(!plan.safety?.eligible)return nav('today');if(state.dayOptions?.[F.dateKey()]?.skip)return toast('今天已选择休息，可在计划页恢复原安排后再开始。');
 if(state.session){nav('session');return;}
 const last=state.history.at(-1);if(last&&Date.now()-last.finishedAt<48*3600000){modal('先给身体恢复时间','<p>距离上次全身力量训练不足 48 小时。今天可以进行舒适的轻活动，等恢复后再练下一次。</p><button class="btn wide" data-action="close" style="margin-top:20px">知道了</button>');return;}
 const w=plan.workouts.find(x=>x.id===id);if(!w)return;
 modal('今天的状态适合开始吗？',`<p>先确认今天没有新出现的疼痛、明显疲劳、发热或异常不适。</p><div class="note">热身 5–8 分钟：轻松走动、舒适活动关节，再用更容易的版本练习今天的动作。负重动作先用很轻重量试做。</div><div class="actions"><button class="btn" data-confirm-start="${id}">状态正常，开始热身</button><button class="btn secondary" data-action="not-ready">今天不太舒服</button></div>`);
}
function confirmStart(id){
 const plan=buildPlan();const last=state.history.at(-1);if(!plan.safety.eligible||state.dayOptions?.[F.dateKey()]?.skip||(last&&Date.now()-last.finishedAt<48*3600000)){closeModal();nav('today');return;}if(state.session){closeModal();nav('session');return;}const w=plan.workouts.find(x=>x.id===id);if(!w)return;
 state.session={id:String(Date.now()),label:w.label,date:F.dateKey(),startedAt:Date.now(),exercises:w.exercises.map(x=>({id:x.id,reps:x.reps,rest:x.rest,targetReps:x.targetReps,weightSuggestion:x.weightSuggestion||'',sets:Array.from({length:x.sets},()=>({weight:E[x.id].load?'':'0',reps:'',done:false}))}))};save();closeModal();nav('session');
}
function renderSession(){
 const s=state.session;if(!s){route='today';return '<div class="card"><p>当前没有未完成的训练。</p><button class="btn" data-nav="today">回到今天</button></div>';}
 const total=s.exercises.reduce((a,x)=>a+x.sets.length,0),done=s.exercises.reduce((a,x)=>a+x.sets.filter(y=>y.done).length,0);
 return `<div class="session-head"><div class="page-head" style="margin:0"><div><span class="eyebrow">正在训练 · ${esc(s.label)}</span><h2 style="margin:5px 0 0">一组一组，慢慢完成。</h2></div><button class="btn secondary small" data-nav="today">暂存返回</button></div><div class="progress-track"><span style="width:${done/total*100}%"></span></div><p class="muted small">已完成 ${done} / ${total} 组 · 勾选后开始休息计时</p></div><div class="note">先热身。哑铃重量填写<strong>单只重量</strong>；徒手动作只填次数。左右交替动作填每侧次数。图示和记录不等于实时动作纠正。</div>${s.exercises.map((x,i)=>{const ex=E[x.id];return `<section class="card"><div class="section-title" style="margin-top:0"><div><span class="eyebrow">动作 ${i+1}</span><h2 style="margin-top:5px">${ex.name}</h2></div><button class="text-button" data-exercise="${x.id}">动作教学</button></div><p class="muted">目标 ${esc(x.reps||ex.reps)} · 休息 ${x.rest||ex.rest} 秒</p><p class="field-help">${esc(x.weightSuggestion||F.progression(x.id,state.history,state.profile.maxDumbbell))}</p><div class="set-row labels"><span>组</span><span>${ex.load?'重量 · kg':'负重'}</span><span>${ex.timed?'秒数':'次数'}</span><span>完成</span></div>${x.sets.map((set,j)=>`<div class="set-row"><span>${j+1}</span>${ex.load?`<input aria-label="${ex.name}第 ${j+1} 组重量" type="number" inputmode="decimal" min="0" max="${ex.equipment.includes('dumbbell')?state.profile.maxDumbbell:300}" step="0.1" value="${esc(set.weight)}" data-set-input="weight" data-i="${i}" data-j="${j}">`:'<span class="small muted" style="text-align:center">徒手 / 带</span>'}<input aria-label="${ex.name}第 ${j+1} 组${ex.timed?'秒数':'次数'}" type="number" inputmode="numeric" min="1" max="200" step="1" value="${esc(set.reps)}" placeholder="实际完成" data-set-input="reps" data-i="${i}" data-j="${j}"><button class="check ${set.done?'checked':''}" aria-label="${set.done?'取消':'标记'}${ex.name}第 ${j+1} 组完成" aria-pressed="${set.done}" data-toggle-set="${i},${j}">✓</button></div>`).join('')}<div class="actions"><button class="btn subtle small" data-rest="${x.rest||ex.rest}">休息 ${x.rest||ex.rest} 秒</button><button class="btn secondary small" data-swap="${i}">换个适合的动作</button></div></section>`;}).join('')}<div class="card"><h2>记录今天的感受</h2><div class="actions"><button class="btn" data-action="finish">结束并保存训练</button><button class="btn danger" data-action="pain-stop">出现疼痛，先停止</button></div><button class="text-button" data-action="discard-session">放弃这次未保存的训练</button></div>`;
}
function toggleSet(i,j){
 const x=state.session.exercises[i],set=x.sets[j],ex=E[x.id];
 if(!set.done){const reps=Number(set.reps),weight=Number(set.weight);if(!Number.isInteger(reps)||reps<1||reps>200)return toast('先填写实际完成的次数或秒数（1–200 的整数）。');if(ex.load&&(set.weight===''||!Number.isFinite(weight)||weight<0||weight>300))return toast('先填写实际使用重量。');if(ex.equipment.includes('dumbbell')&&weight>Number(state.profile.maxDumbbell))return toast('这个重量超过你填写的单只哑铃上限。');}
 set.done=!set.done;save();render();if(set.done)startTimer(x.rest||ex.rest);
}
function startTimer(seconds){
 timerEnd=Date.now()+seconds*1000;clearInterval(timerInterval);tick();timerInterval=setInterval(tick,250);
 function tick(){const left=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));$('#timer').hidden=false;$('#timer').innerHTML=`<div class="small">${left?'组间休息':'休息结束 · 按感受继续'}</div><strong>${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}</strong><button data-action="timer-add">+30秒</button><button data-action="timer-close" aria-label="关闭休息计时">×</button>`;if(!left){clearInterval(timerInterval);toast('休息时间到了，感觉没恢复可以再休息。');}}
}
function stopTimer(){clearInterval(timerInterval);timerEnd=0;$('#timer').hidden=true;}
function finishDialog(pain=false){
 const s=state.session;if(!s)return;
 const completed=s.exercises.reduce((a,x)=>a+x.sets.filter(y=>y.done).length,0);
 if(!completed&&!pain){toast('还没有完成记录。填写并勾选做完的组，或放弃本次训练。');return;}
 modal(pain?'先停止，不要忍痛继续':'保存这一次训练',`${pain?'<div class="note danger">停止引发疼痛的动作。尖锐痛、持续痛、麻木需要专业评估；若正在胸痛、晕厥或严重气短，应寻求急救帮助。</div>':''}<p>已勾选完成 ${completed} 组，未勾选的组会保留为未完成。</p><form id="finish-form"><label class="field-label" style="margin-top:18px">整体用力感受</label><div class="choices">${[['easy','比较轻松'],['right','刚刚好'],['hard','偏吃力']].map(([v,t])=>choice('effort',v,t,'',false)).join('')}</div>${selectField("recovery","今天整体精力和恢复感受",[["","请选择"],["good","精力尚可，感觉恢复正常"],["tired","有些疲劳，希望下次轻一点"],["poor","明显疲劳，恢复不足"]],"")}<label class="inline-label"><input type="checkbox" name="pain" ${pain?'checked':''}>本次出现了疼痛或异常不适</label><label class="field"><span class="field-label">想记住的事（可选）</span><textarea name="note" maxlength="500" placeholder="例如：深蹲后半程动作不太稳定"></textarea></label><div class="form-error" id="finish-error"></div><button class="btn wide" type="submit">保存训练记录</button></form>`);
 $('#finish-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);if(!fd.get('effort')||!fd.get('recovery')){$('#finish-error').textContent='请选择整体用力感受和恢复情况。';return;}
 const totalSets=s.exercises.reduce((a,x)=>a+x.sets.length,0);const item={...structuredClone(s),date:F.dateKey(),finishedAt:Date.now(),completedSets:completed,totalSets,effort:fd.get('effort'),recovery:fd.get('recovery'),pain:fd.has('pain'),note:fd.get('note')};state.history.push(item);state.session=null;save();stopTimer();closeModal();nav('record');toast('本次训练已记录，下一次安排会参考你的反馈。');});
}
function swapDialog(index){
 const s=state.session,x=s.exercises[index],original=E[x.id],p=state.profile;
 if(x.sets.some(y=>y.done)){toast('这个动作已有完成记录。请保留本次记录，下次训练再换。');return;}
 const choices=F.alternatives(p,x.id,state.history).map(id=>E[id]).filter(e=>!s.exercises.some(y=>y.id===e.id));
 modal('选择同类替代动作',`<p class="muted">只列出你现有器材能做的动作。动作疼痛时先停止，不用换动作硬练。</p>${choices.length?choices.map(e=>`<div class="exercise-row"><div class="exercise-title"><h3>${e.name}</h3><p>${e.muscle}</p></div><button class="btn secondary small" data-replace="${index},${e.id}">换成这个</button></div>`).join(''):'<div class="note">当前没有其他匹配动作。可以跳过不适合的动作，保留未完成记录。</div>'}`);
}
function showSources(){modal('依据与开源说明',`<p class="source-date">核验日期：2026-09-27。机构指南提供一般原则；本工具的具体排课与饮食组合为原创的保守应用规则。</p><ol class="source-list">${SOURCES.map(s=>`<li><a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.title}</a><p class="source-date">${s.date}</p><p class="small muted">${s.use}</p></li>`).join('')}</ol><h3>参考过的产品</h3><p class="small"><a href="https://www.calorietech.com/" target="_blank" rel="noopener noreferrer">Keep：目标评估、日程、跟练与反馈流程</a>；<a href="https://www.hevyapp.com/features/" target="_blank" rel="noopener noreferrer">Hevy：组数记录、休息计时和训练历史</a>；<a href="https://github.com/wger-project/wger" target="_blank" rel="noopener noreferrer">wger：开源训练与营养管理</a>。仅借鉴工作流程，不复制界面或承诺其付费功能免费。</p><h3 style="margin-top:18px">适用边界</h3><p class="small">这是个人入门辅助工具，未经过临床验证、不能诊断疾病或实时识别动作。需要康复、特殊人群指导或更高阶训练时，请找具有相应资质的专业人员。</p><p class="small"><a href="EXERCISE-LICENSE.txt" target="_blank">查看动作素材许可证</a></p>`);}
function showHelp(){modal('手机和电脑怎么用',`<h3>苹果手机</h3><ol><li>用 Safari 打开自在练的免费网址。</li><li>点“分享 → 添加到主屏幕”，以后可从图标打开。</li><li>在工具里填写和补充资料，生成安排后进入“今天”或“计划”。</li></ol><h3>电脑</h3><ol><li>用电脑浏览器打开同一个网址，不需要安装软件。</li><li>可以收藏网页，使用鼠标或键盘查看计划、动作和饮食，记录训练。</li><li>页面会根据窗口宽度调整；电脑和手机的功能都在导航里。</li></ol><div class="note"><strong>在两台设备看同一份资料</strong><p>在已填写的设备进入“我的 → 导出备份”，把文件保存并传到另一台设备，再点“导入备份”。导入会替换接收设备的记录，请先保留它自己的备份。</p><p>这里没有自动云同步。备份包含身体资料，请自行保管，不要公开分享。</p></div><p>使用正式免费网址不需要电脑一直开机。Safari 和主屏幕版本也可能使用不同存储，请在原入口备份。基本页面可缓存，首次访问和外部学习资料需要联网；锁屏后台的计时提醒可能被系统暂停。</p><p class="small"><a href="https://support.apple.com/zh-cn/guide/iphone/iphea86e5236/ios" target="_blank" rel="noopener noreferrer">苹果官方：将网站变为 App</a></p>`);}
function showBasics(){modal('从零认识训练',`<ul><li><strong>次数：</strong>完整做一遍动作算 1 次。</li><li><strong>组数：</strong>连续做完一串次数算 1 组。例如 2 组 × 10 次，就是做 10 次，休息，再做 10 次。</li><li><strong>余力：</strong>做完还觉得能用好姿势再做约 3 次。不是憋气硬撑到完全做不动。</li><li><strong>选重量：</strong>先轻、先试。目标次数内不能控制动作就减轻，不用按体重猜一个“该举多少”的数。</li><li><strong>呼吸：</strong>通常用力阶段呼气，还原阶段吸气，避免长时间憋气。</li><li><strong>酸与痛：</strong>肌肉用力感不等于关节痛。尖锐痛、麻木或异常不适要停。</li></ul><div class="note">记录的目的是帮助下次选择，不是为了每次都破纪录。</div>`);}
function download(name,text,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
function exportData(){download(`自在练-备份-${F.dateKey()}.json`,JSON.stringify(state,null,2));toast('已发起备份下载，请在浏览器下载或“文件”里确认。');}
function validateBackup(v){
 if(!v||typeof v!=='object'||v.version!==1||!Array.isArray(v.history)||!Array.isArray(v.measurements)||v.history.length>10000||v.measurements.length>10000)throw Error('不是有效的自在练备份。');
 if(v.profile&&F.validateProfile(v.profile).length)throw Error('备份里的个人资料不完整或无效。');
 const date=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
 for(const x of v.measurements)if(!date(x.date)||!Number.isFinite(x.weight)||x.weight<25||x.weight>250||(x.waist!==null&&(!Number.isFinite(x.waist)||x.waist<30||x.waist>250)))throw Error('身体记录的格式不正确。');
 for(const h of [...v.history,...(v.session?[v.session]:[])]){
  if(!date(h.date)||typeof h.label!=='string'||!Array.isArray(h.exercises)||h.exercises.length>30)throw Error('训练记录的格式不正确。');
  for(const x of h.exercises){if(!E[x.id]||!Array.isArray(x.sets)||x.sets.length>20)throw Error('训练动作无效。');for(const s of x.sets)if(typeof s.done!=='boolean'||!['string','number'].includes(typeof s.reps)||!['string','number'].includes(typeof s.weight)||(s.done&&(!Number.isInteger(Number(s.reps))||Number(s.reps)<1||Number(s.reps)>200||!Number.isFinite(Number(s.weight))||Number(s.weight)<0||Number(s.weight)>300)))throw Error('训练组记录无效。');}
 }
 for(const h of v.history)if(!Number.isFinite(h.finishedAt)||!Number.isInteger(h.completedSets)||!Number.isInteger(h.totalSets)||!['easy','right','hard'].includes(h.effort)||typeof h.pain!=='boolean')throw Error('训练结果格式不正确。');
 if(v.draft&&(!v.draft.health||!Array.isArray(v.draft.equipment)||!Array.isArray(v.draft.days)))throw Error('填写草稿格式错误。');
 const allowed={...blank(),profile:v.profile||null,draft:v.draft||null,history:v.history,measurements:v.measurements,session:v.session||null,dayOptions:v.dayOptions&&typeof v.dayOptions==='object'&&!Array.isArray(v.dayOptions)?v.dayOptions:{},mealChecks:v.mealChecks&&typeof v.mealChecks==='object'?v.mealChecks:{}};
 for(const [day,opt] of Object.entries(allowed.dayOptions))if(!date(day)||!opt||typeof opt!=='object'||(opt.minutes!=null&&![20,30,45,60].includes(Number(opt.minutes)))||typeof opt.skip!=='undefined'&&typeof opt.skip!=='boolean')delete allowed.dayOptions[day];
 return JSON.parse(JSON.stringify(allowed));
}
function importData(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.size>5*1024*1024)return toast('备份超过 5 MB，请检查文件是否正确。');try{const pending=validateBackup(JSON.parse(await file.text()));modal('确认恢复备份',`<p>这份备份包含 ${pending.history.length} 次训练、${pending.measurements.length} 条身体记录。</p><p>恢复会替换当前浏览器内的数据。请先导出当前记录，避免丢失。</p><div class="actions"><button class="btn secondary" id="export-current">先导出当前数据</button><button class="btn" id="confirm-import">确认替换并恢复</button></div>`);$('#export-current').onclick=exportData;$('#confirm-import').onclick=()=>{state=pending;sceneChoice=null;loadError=false;draft=state.draft||defaultDraft();step=0;editMode=false;reviewMode=false;save();closeModal();nav('today');toast('备份已恢复。');};}catch(e){toast('恢复失败：'+e.message);}};input.click();}
document.addEventListener('click',e=>{
 const b=e.target.closest('button,a[data-nav]');if(!b)return;
 if(b.dataset.nav)return nav(b.dataset.nav);
 if(b.dataset.exercise)return showExercise(b.dataset.exercise);
 if(b.dataset.calendarWorkout){const plan=buildPlan();planTab=Math.max(0,plan.workouts.findIndex(w=>w.id===b.dataset.calendarWorkout));nav('plan');return;}
 if(b.dataset.plan!=null){planTab=Number(b.dataset.plan);render();return;}
 if(b.dataset.mealDay!=null){mealDay=Number(b.dataset.mealDay);render();const weekly=$('.weekly-food');weekly.open=true;weekly.querySelector(`[data-meal-day="${mealDay}"]`)?.focus({preventScroll:true});return;}
 if(b.dataset.start)return beginWorkout(b.dataset.start);
 if(b.dataset.confirmStart)return confirmStart(b.dataset.confirmStart);
 if(b.dataset.toggleSet){const [i,j]=b.dataset.toggleSet.split(',').map(Number);return toggleSet(i,j);}
 if(b.dataset.rest)return startTimer(Number(b.dataset.rest));
 if(b.dataset.swap!=null)return swapDialog(Number(b.dataset.swap));
 if(b.dataset.replace){const [idx,id]=b.dataset.replace.split(','),old=state.session?.exercises[Number(idx)];if(!old||!F.alternatives(state.profile,old.id,state.history).includes(id)||old.sets.some(x=>x.done))return;const ex=E[id],sameUnit=Boolean(E[old.id].timed)===Boolean(ex.timed),fallback=5,targetReps=Math.min(ex.maxReps||12,sameUnit?Number(old.targetReps)||fallback:fallback);state.session.exercises[Number(idx)]={id,targetReps,reps:`${ex.reps.includes('每侧')?'每侧 ':''}${targetReps} ${ex.timed?'秒':'次'}`,rest:Math.max(old.rest||0,ex.rest),weightSuggestion:ex.load?'换动作后从很轻、可控制的重量试起，仍应能多做约 3 次。':'使用能稳定完成的幅度与姿势，不追求极限。',sets:old.sets.map(()=>({weight:ex.load?'':'0',reps:'',done:false}))};save();closeModal();render();return;}
 if(b.dataset.history!=null){const i=Number(b.dataset.history),h=state.history[i];modal(`${h.date} · ${h.label}`,`<p class="muted">${h.pain?'有疼痛 / 不适':'无疼痛记录'} · ${esc(h.note||'没有补充备注')}</p>${h.exercises.map(x=>`<div class="meal"><h3>${E[x.id].name}</h3><p>${x.sets.map((s,j)=>`第 ${j+1} 组：${s.done?`${E[x.id].load?esc(s.weight)+' kg × ':''}${esc(s.reps)} ${E[x.id].timed?'秒':'次'}`:'未完成'}`).join('<br>')}</p></div>`).join('')}<button class="btn danger wide" data-delete-history="${i}" style="margin-top:20px">删除这次记录</button>`);return;}
 if(b.dataset.deleteHistory!=null){const i=Number(b.dataset.deleteHistory);modal('删除这次训练记录？','<p>仅删除这一次，其他记录保留。删除前可以先导出备份。</p><div class="actions"><button class="btn secondary" data-action="close">保留</button><button class="btn danger" id="confirm-delete-history">确认删除</button></div>');$('#confirm-delete-history').onclick=()=>{state.history.splice(i,1);save();closeModal();render();};return;}
 if(b.dataset.deleteMeasure){const date=b.dataset.deleteMeasure;modal('删除这条身体记录？',`<p>将删除 ${esc(date)} 的体重和腰围记录。</p><div class="actions"><button class="btn secondary" data-action="close">保留</button><button class="btn danger" id="confirm-delete-measure">确认删除</button></div>`);$('#confirm-delete-measure').onclick=()=>{state.measurements=state.measurements.filter(x=>x.date!==date);save();closeModal();render();};return;}
 const action=b.dataset.action;
 if(action==='measurement-entry'){nav('record');const form=$('#measurement-form');form?.scrollIntoView({block:'start'});form?.querySelector('[name=weight]')?.focus({preventScroll:true});}
 if(action==='close')closeModal();
 if(action==='help')showHelp();
 if(action==='sources')showSources();
 if(action==='scene-next'){const result=FitFood.recommend(state.profile,F.nutrition(state.profile,state.history,state.measurements),foodSceneSelection());if(result.status!=='ready'||!result.hasMore)return;sceneChoice.variant++;render();$('[data-action=scene-next]')?.focus({preventScroll:true});}
 if(action==='skip-today'||action==='unskip-today'){if(state.session)return toast('请先保存或放弃正在进行的训练。');state.dayOptions??={};const date=F.dateKey();state.dayOptions[date]={...state.dayOptions[date],skip:action==='skip-today'};save();render();toast(action==='skip-today'?'今天改为恢复日，后面按原日程继续，不用补练。':'已恢复今天原来的安排。');}
 if(action==='basics')showBasics();
 if(action==='edit'||action==='review-screening'||action==='lean-goal'){if(state.session){toast('请先完成或放弃未结束的训练，再修改资料。');return;}draft={...defaultDraft(),...structuredClone(state.profile)};editMode=true;reviewMode=action==='review-screening'||action==='lean-goal';if(action==='lean-goal'){draft.goal='lean';draft.weightStrategy||='auto';}step=action==='lean-goal'?1:reviewMode&&['1','3','4'].includes(b.dataset.reviewStep)?Number(b.dataset.reviewStep):0;render();window.scrollTo(0,0);if(reviewMode&&b.dataset.reviewHealth){const input=$(`[name="health_${b.dataset.reviewHealth}"]:checked`);if(input){input.closest('fieldset').classList.add('focus-card');input.closest('fieldset').scrollIntoView({block:'center'});input.focus({preventScroll:true});}}}
 if(action==='cancel-edit'||action==='cancel-review'){editMode=false;reviewMode=false;draft={...defaultDraft(),...structuredClone(state.profile)};state.draft=null;save();render();window.scrollTo(0,0);}
 if(action==='setup-back'){readDraft();save();step--;renderSetup();window.scrollTo(0,0);}
 if(action==='warmup')modal('热身与结束放松','<ol><li>轻松走动或原地踏步 2–3 分钟。</li><li>在舒适范围活动肩、髋、膝、踝。</li><li>用更轻重量或更容易版本，练习当天前几个动作各 5–8 次。</li><li>结束后慢走 3–5 分钟，呼吸平稳再离开。</li></ol><p class="field-help">有疼痛的动作不靠热身硬顶过去。</p>');
 if(action==='not-ready'){closeModal();modal('今天可以先休息','<p>有新的疼痛、发热或异常不适时，先不训练。持续或反复出现的情况需要专业评估；严重症状及时就医。</p>');}
 if(action==='finish')finishDialog();
 if(action==='pain-stop'){stopTimer();finishDialog(true);}
 if(action==='discard-session'){modal('放弃这次训练？','<p>本次未保存的组数会被移除，以前的训练记录保留。</p><div class="actions"><button class="btn secondary" data-action="close">继续保留</button><button class="btn danger" id="confirm-discard">确认放弃</button></div>');$('#confirm-discard').onclick=()=>{state.session=null;save();stopTimer();closeModal();nav('today');};}
 if(action==='timer-add'){startTimer(Math.max(0,Math.ceil((timerEnd-Date.now())/1000))+30);}
 if(action==='timer-close')stopTimer();
 if(action==='export')exportData();
 if(action==='import')importData();
 if(action==='raw-backup'){let raw='';try{raw=localStorage.getItem(STORE)||'空数据';}catch(_){}download('自在练-原始数据备份.txt',raw,'text/plain');}
 if(action==='reset-corrupt'){loadError=false;state=blank();sceneChoice=null;draft=defaultDraft();save();closeModal();step=0;renderSetup();}
 if(action==='reset'){modal('清空当前浏览器的全部记录？','<p>将移除个人资料、训练历史、饮食勾选和身体记录。这个操作无法撤销；建议先导出备份。</p><div class="actions"><button class="btn secondary" data-action="export">先导出备份</button><button class="btn danger" id="confirm-reset">确认全部清空</button></div>');$('#confirm-reset').onclick=()=>{state=blank();sceneChoice=null;draft=defaultDraft();step=0;editMode=false;save();stopTimer();closeModal();nav('today');};}
 if(action==='energy'){const n=F.nutrition(state.profile,state.history,state.measurements);modal('热量估算，怎样理解',`<p>先用年龄、身高、体重和生理性别估算静息能量，再乘你选择的日常活动系数。</p><div class="note">本次：静息约 ${n.rest} 千卡 × ${n.factor} ≈ 维持量 ${n.maintenance} 千卡。增肌起点约增加 5%，减脂约减少 10%；体型改善和健康目标先按维持量。</div><p>这些是估算假设，不是实际测量。活动系数已粗略考虑一般活动，不再把运动消耗额外加一遍。先按体重趋势、饥饿和训练表现复盘，不根据一天波动调整。</p>`);}
 if(action==='weight-method')modal('薄肌与体重方向，怎样判断','<p>薄肌是外形偏好，体重方向单独判断。BMI 只作初步筛查，不能区分肌肉和脂肪，也不会据此给出体脂率。</p><p>适用时，小幅增重使用估算维持量上方的少量余量，先维持则使用维持量起点。均是估算；复盘建议不会按天自动叠加热量。</p><p>趋势比较多个日期的平均体重，结合可选腰围、相同动作的表现和恢复。至少两周且两段均有多次测量才比较；记录太少、过旧、波动异常时会明确提示。腰围变化与力量进步也不能证明增加的重量全是肌肉。</p><p>关于“过快”或“需观察”的提示是本工具的保守复盘规则，不是疾病诊断或研究给个人规定的理想增重速度。特殊饮食、异常消瘦等先走相应评估。</p><button class="text-button" data-action="sources">查看依据与适用范围</button>');
 if(action==='waist-help')modal('腰围怎么量','<ol><li>站立放松，找到最下方肋骨和髋骨上缘，两者中间的位置作为测量位置。</li><li>软尺绕身体一圈，保持水平、贴身但不勒紧皮肤。</li><li>自然呼气后读数，不收腹、不过度憋气。每次尽量使用相同位置和测量条件。</li></ol><p>腰围可以不填。它只能帮助观察长期变化，不能直接算出精确体脂率。</p><p><a href="https://elht.nhs.uk/services/dietetics/body-measuring-techniques" target="_blank" rel="noopener noreferrer">查看 NHS 医院测量说明（英文）</a></p>');
 if(action==='protein')modal('蛋白质克数不是食物重量','<p>例如某食品标签写“每 100 克含蛋白质 10 克”，吃 200 克就得到约 20 克蛋白质。这只是读标签的算例，并非特定食物的营养数据。</p><p>把三餐食物的蛋白质相加，再和你的范围比较。普通食物可以完成目标，不需要为了使用这个工具购买蛋白粉。</p>');
});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.setInput&&state.session){const set=state.session.exercises[Number(t.dataset.i)].sets[Number(t.dataset.j)];set[t.dataset.setInput]=t.value;if(set.done){set.done=false;const check=t.closest('.set-row').querySelector('.check');check.classList.remove('checked');check.setAttribute('aria-pressed','false');const ex=E[state.session.exercises[Number(t.dataset.i)].id];check.setAttribute('aria-label',`标记${ex.name}第 ${Number(t.dataset.j)+1} 组完成`);const total=state.session.exercises.reduce((a,x)=>a+x.sets.length,0),done=state.session.exercises.reduce((a,x)=>a+x.sets.filter(y=>y.done).length,0);$('.session-head .progress-track span').style.width=(done/total*100)+'%';$('.session-head p').textContent=`已完成 ${done} / ${total} 组 · 勾选后开始休息计时`;}save();}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.sceneSelect){const key=t.dataset.sceneSelect,valid={place:FitFood.PLACES,meal:FitFood.MEALS,context:FitFood.CONTEXTS};if(!valid[key]||!Object.hasOwn(valid[key],t.value))return;const id=t.id;foodSceneSelection()[key]=t.value;sceneChoice.variant=0;render();document.getElementById(id)?.focus({preventScroll:true});return;}if(t.id==='today-minutes'){state.dayOptions??={};const date=F.dateKey();state.dayOptions[date]={...state.dayOptions[date],minutes:Number(t.value)};save();render();toast('已按今天的时间重新安排，长期设置保持不变。');}if(t.dataset.foodCheck){state.mealChecks[F.dateKey()]??={};state.mealChecks[F.dateKey()][t.dataset.foodCheck]=t.checked;save();}});
document.addEventListener('submit',e=>{if(e.target.id!=='measurement-form')return;e.preventDefault();const fd=new FormData(e.target),weight=Number(fd.get('weight')),waist=fd.get('waist')===''?null:Number(fd.get('waist')),date=String(fd.get('date'));if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date||date>F.dateKey()||!Number.isFinite(weight)||weight<25||weight>250||(waist!==null&&(waist<30||waist>250))){$('#measure-error').textContent='请检查日期、体重和腰围。';return;}state.measurements=state.measurements.filter(x=>x.date!==date);state.measurements.push({date,weight,waist});state.measurements.sort((a,b)=>a.date.localeCompare(b.date));save();render();toast('身体记录已保存。');});
$('#help-button').onclick=showHelp;
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&timerEnd&&timerEnd<=Date.now()){stopTimer();toast('休息时间已经结束，请按身体感受继续。');}});
render();
if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'navigate_fitness_section',title:'打开健身工具页面',description:'只切换到指定页面，不修改或输出健康资料。',inputSchema:{type:'object',properties:{section:{type:'string',enum:['today','plan','food','record','profile']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!['today','plan','food','record','profile'].includes(input.section))throw Error('页面无效');nav(input.section);return{opened:input.section,profileRequired:!state.profile};}});}catch(_){}}
